### ISSUE TITLE
Usage on servers

### ISSUE THREAD

**Issue by pavog** [jaredlll08/InitialInventory#14]
Hi, I use [InitialInventory-fabric-1.18.2-6.0.8.jar](https://www.curseforge.com/minecraft/mc-mods/initial-inventory/files/3757616)  on my fabric 1.18.2 (0.14.6) server.
I want to know where I have to create the config file?

Is it <server dir>/scripts?
And how should the file be named?

**Comment by jaredlll08** [comment]
The mod uses CraftTweaker for functionality, you can find out more about scripts files here
https://docs.blamejared.com/1.18/en/tutorial/IntroductionToScripting/WhatAreScripts

They can have any *reasonable* name as long as it ends in `.zs`

If you need any help, you can join https://discord.blamejared.com and ask there as well
