### ISSUE TITLE
No such symbol: mods

### ISSUE THREAD

**Issue by finnglink** [jaredlll08/InitialInventory#16]
I've installed the mod + FauxCustomEntityData and used this script:
"mods.initialinventory.InvHandler.addStartingItem("apples", <item:minecraft:apple>);"
Named "startingInventory.zs" and put in the scripts folder.

Upon joining I get the following error:
"initialInventory.zs:2:0: no such symbol: mods"

What's causing this?

Best,
Finn

**Comment by jaredlll08** [comment]
Upload your crafttweaker.log file and your script file please

**Comment by jaredlll08** [comment]
Closing due to no reply.
