### ISSUE TITLE
[Crash] i can't load game.

### ISSUE THREAD

**Issue by bontavi** [jaredlll08/InitialInventory#2]
MC - 1.10.2
lootTweaker - 0.0.1
Initial Inventory - 1.0.1
Forge - 12.18.3.220.2
Pastebin - http://pastebin.com/V6YCVKTF

I have added loottweaker to modpack and it doesn't allow me to load game.

I have tried to disable Initial Inventory -  game loaded .
I did same with disabled lootTweaker and left Initial Inventory to work - game loaded .

**Comment by jaredlll08** [comment]
Loot tweaker issue.
