### ISSUE TITLE
Order Functionality Not Working

### ISSUE THREAD

**Issue by Amaxter** [jaredlll08/InitialInventory#4]
Randomizes order no matter what config values I set for numbers

`# Adds the custom initial inventory for the player to make starting out easier
mods.initialinventory.InvHandler.addStartingItem(<minecraft:stone_pickaxe>, 1);
mods.initialinventory.InvHandler.addStartingItem(<minecraft:stone_sword>, 2);
mods.initialinventory.InvHandler.addStartingItem(<minecraft:stone_axe>, 3);
mods.initialinventory.InvHandler.addStartingItem(<minecraft:stone_shovel>, 4);
mods.initialinventory.InvHandler.addStartingItem(<minecraft:shears>, 5);
mods.initialinventory.InvHandler.addStartingItem(<tconstruct:book>, 6);
mods.initialinventory.InvHandler.addStartingItem(<tconstruct:tooltables:0>, 7);
mods.initialinventory.InvHandler.addStartingItem(<realistictorches:matchbox>, 8);`

results in

https://goo.gl/30Ri9o

**Comment by jaredlll08** [comment]
Fixed in latest release
https://minecraft.curseforge.com/projects/initial-inventory/files/2416695
