### ISSUE TITLE
Item duplication glitch

### ISSUE THREAD

**Issue by GeoRCCraft** [jaredlll08/InitialInventory#5]
I found this glitch while working on Caved IN. I am using Minecraft 1.10.2 with Initial Inventory 1.0.1, MT Lib 1.0.3, and Craft Tweaker 3.0.25. The following is a video I made as well as my script that I used to showcase this issue.

mods.initialinventory.InvHandler.addStartingItem(<minecraft:torch>, 7);
mods.initialinventory.InvHandler.addStartingItem(<minecraft:bread> *5, 8);

https://www.youtube.com/watch?v=OPdWTt8dU28&feature=youtu.be

**Comment by jaredlll08** [comment]
Video is gone, 1.10 is old, not much I can do now. sorry
