### ISSUE TITLE
Not working on 1.15.2 and causing error in CraftTweaker

### ISSUE THREAD

**Issue by rckymtnrfc** [jaredlll08/InitialInventory#7]
Forge 31.1.46
Initial Inventory 5.0.0

When loading up a new single player world, I'm not receiving any inventory item.  The script is named initial_inventory.zs and contains the follow:

mods.initialinventory.InvHandler.addStartingItem(<minecraft:stick>);

I'm also getting an error from CraftTweaker because it tries to load the script.  (https://pastebin.com/6bUuX9ma)

LMK if you need anything else from me to track down the issue.

And thanks for the 1.15.2 update!

**Comment by jaredlll08** [comment]
post script in pastebin.

**Comment by rckymtnrfc** [comment]
Here you go

https://pastebin.com/yEmcpFpM

**Comment by jaredlll08** [comment]
https://docs.blamejared.com/1.14/en/mods/InitialInventory/InitialInventory/

**Comment by rckymtnrfc** [comment]
Thanks, I was going by the description on Curse.  I didn't realize the docs had been added to CraftTweaker.
