### ISSUE TITLE
Give the initial items several times to the same player 1.15.2

### ISSUE THREAD

**Issue by BigShadow155** [jaredlll08/InitialInventory#8]
Forge version 31.1.37
The mod works and gives us the item when a new player enters but from time to time it gives the initial items back to a player who has already given them. What can I do to prevent this from happening?

This is the syntax I have in the .zs file:
#mods.initialinventory.InvHandler.addStartingItem(String key, IItemStack item, Optional int index);
mods.initialinventory.InvHandler.addStartingItem("pan", <item:minecraft:bread> * 5);
mods.initialinventory.InvHandler.addStartingItem("espada", <item:minecraft:iron_sword>);
mods.initialinventory.InvHandler.addStartingItem("pico", <item:minecraft:iron_pickaxe>);
mods.initialinventory.InvHandler.addStartingItem("casco hierro", <item:minecraft:iron_helmet>);
mods.initialinventory.InvHandler.addStartingItem("pechera hierro", <item:minecraft:iron_chestplate>);
mods.initialinventory.InvHandler.addStartingItem("grebas hierro", <item:minecraft:iron_leggings>);
mods.initialinventory.InvHandler.addStartingItem("botas hierro", <item:minecraft:iron_boots>);
mods.initialinventory.InvHandler.addStartingItem("moneda", <item:simplecoins:coin> * 5);

**Comment by jaredlll08** [comment]
What do you mean by "from time to time"

It should only give items multiple times if the key had changed, or if the payers nbt is reset

**Comment by BigShadow155** [comment]
I mean, sometimes it gives the items back to the players and other times he doesn't. And i dont know why.
I have a server shutdown system for scheduled maintenance every day. Is it possible that's why?

What do you mean by " players nbt is reset".

**Comment by Dumdidldum** [comment]
I can confirm this
This happens on my server as well
We are on Forge 31.2.5
In my case it does not seem to correlate with server restarts but it seems to have something to do with players dieing (but not always)
The server console does not show anything as far as i can see...
